<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>LineScope.App</RootNamespace>
    <AssemblyName>LineScope</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.1</Version>
    <Product>LineScope</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LineScope.Core\LineScope.Core.csproj" />
  </ItemGroup>

</Project>
